sudo: required
services:
- docker

before_install:
- docker build -t dwright101/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run dwright101/react-test npm test -- --coverage

after_success:
- docker build -t dwright101/ott-app-client ./client
- docker build -t dwright101/ott-app-nginx ./nginx
- docker build -t dwright101/ott-app-server ./server
- docker build -t dwright101/ott-app-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push dwright101/ott-app-client
- docker push dwright101/ott-app-nginx
- docker push dwright101/ott-app-server
- docker push dwright101/ott-app-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  name: "ott-app"
  env: "OttApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-951598467679"
  bucket_path: "ott-app"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 